# Generated by Django 5.2 on 2025-04-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GardenOfMelon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
