# Generated by Django 5.2 on 2025-04-17 11:46

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GardenOfMelon', '0002_remove_user_birthday_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+639123456789', max_length=128, region=None),
        ),
    ]
