# Generated by Django 5.2 on 2025-04-20 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GardenOfMelon', '0004_product_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
