# Generated by Django 5.2 on 2025-05-16 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GardenOfMelon', '0018_remove_shippingaddress_date_added_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='state',
            new_name='region',
        ),
    ]
