# Generated by Django 5.2 on 2025-05-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GardenOfMelon', '0019_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
