# Generated by Django 5.2 on 2025-05-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GardenOfMelon', '0021_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled'), ('Return/Refund', 'Return/Refund')], default='Pending', max_length=20),
        ),
    ]
