# Generated by Django 5.2 on 2025-05-19 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GardenOfMelon', '0023_alter_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='complete',
        ),
    ]
