# Generated by Django 5.2 on 2025-05-19 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GardenOfMelon', '0026_alter_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='region',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='zipcode',
        ),
    ]
