# Generated by Django 5.2 on 2025-05-19 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GardenOfMelon', '0027_remove_customer_address_remove_customer_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GardenOfMelon.customer'),
        ),
    ]
